### ISSUE TITLE
Could RSS feed posts link to episode pages?

### ISSUE THREAD

**Issue by brianeray** [codereport/adsp2#4]
Is it possible for each RSS entry to include a direct link to the episode page? The RSS posts include the whole MP3, which is great, and the post itself is naturally a slimmed-down variant of the corresponding episode page. I just wish I could click out from an RSS post to the episode page, because I use the player widget to listen in.

And thanks to Conor and Bryce for the excellent podcast. It's almost always outside my own engineering domain but it's great to hear about other languages and other problem spaces.

**Comment by codereport** [comment]
Hi Brian, 

Do you mean including a URL link to the website show notes in the show notes? e.g for the latest episode 86 including the link https://adspthepodcast.com/2022/07/15/Episode-86.html in the show notes?

**Comment by brianeray** [comment]
Yes, exactly.

**Comment by codereport** [comment]
Will do going forward!
